In [43]:
import pandas as pd

df = pd.read_csv("Mobile_data.csv")
df.drop(columns =["best_price"], axis =0 )

,Unnamed: 0,brand_name,model_name,os,popularity,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,NaN,NaN,10,5.71,16.0,3000.0,20-Apr
...,...,...,...,...,...,...,...,...,...,...,...,...
1219,1219,Apple,iPhone XS Max 64GB Gold (MT522),iOS,1101,16018.0,27900.0,61,6.50,64.0,3174.0,18-Sep
1220,1220,Apple,iPhone XS Max Dual Sim 64GB Gold (MT732),iOS,530,21939.0,33720.0,28,6.50,64.0,3174.0,18-Sep
1221,1221,HUAWEI,nova 5T 6/128GB Black (51094MEU),Android,1174,7999.0,9999.0,18,6.26,128.0,3750.0,19-Nov
1222,1222,ZTE,nubia Red Magic 5G 8/128GB Black,Android,752,18500.0,19010.0,2,6.65,128.0,4500.0,20-Oct
1223,1223,Sigma mobile,x-style 35 Screen,NaN,952,785.0,944.0,75,3.50,NaN,1750.0,20-Jan

In [44]:
import pandas as pd

df = pd.read_csv("Mobile_data.csv")
df.head()

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr

In [45]:
import pandas as pd

df = pd.read_csv("Mobile_data.csv")
df.drop(columns =["best_price"], inplace = True )   #remove data
df.head()

,Unnamed: 0,brand_name,model_name,os,popularity,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,NaN,NaN,10,5.71,16.0,3000.0,20-Apr

In [46]:
import pandas as pd

dff = pd.read_csv("Mobile_data.csv")

# Show unique brand names
print(dff["brand_name"].unique())

<StringArray>
[     'ALCATEL',        'Nokia',        'Honor',        'Meizu',
       'realme',      'OnePlus',       'Archos',      'Ulefone',
          'AGM',         'OPPO',        'Astro',       'Rezone',
    'Blackview',       'Bravis',          'NUU',       'Lenovo',
      'UMIDIGI',    'Assistant',    'Crosscall',        'Sharp',
         'ERGO',        'Tecno',          'CAT',       'DOOGEE',
       'Xiaomi',          'ZTE',      'Oukitel',        'Cubot',
       'S-TELL', 'Sigma mobile',      'Coolpad',       'Bluboo',
           'LG',     'Motorola',      'Philips',           '2E',
          'Fly',      'Samsung',    'Prestigio',      'myPhone',
   'BlackBerry',      'KENEKSI',       'Maxcom',       'HUAWEI',
       'Vernee',      'General',       'Globex',      'Smartex',
       'Google',         'ASUS',         'Land',        'MAFAM',
        'Jinga',     'Vodafone',    'Microsoft',     'iOutdoor',
     'Elephone',          'HTC',        'Viaan',         'vivo',
         'Sony',       'LEAGOO',         'Nomi',        'Apple']
Length: 64, dtype: str

In [47]:
dff["os"].unique()              # show unique values in 'os' column

dff.loc[dff["brand_name"]=="vivo"]   # filter rows where brand_name is vivo
dff["os"].value_counts()

os
Android         915
iOS             103
OxygenOS          3
WindowsPhone      3
EMUI              2
KAIOS             1
Name: count, dtype: int64

In [48]:
print("the total brands are:", dff["brand_name"].unique())
dff["brand_name"].unique()
dff[dff["os"]=="KAIOS"]

the total brands are: <StringArray>
[     'ALCATEL',        'Nokia',        'Honor',        'Meizu',
       'realme',      'OnePlus',       'Archos',      'Ulefone',
          'AGM',         'OPPO',        'Astro',       'Rezone',
    'Blackview',       'Bravis',          'NUU',       'Lenovo',
      'UMIDIGI',    'Assistant',    'Crosscall',        'Sharp',
         'ERGO',        'Tecno',          'CAT',       'DOOGEE',
       'Xiaomi',          'ZTE',      'Oukitel',        'Cubot',
       'S-TELL', 'Sigma mobile',      'Coolpad',       'Bluboo',
           'LG',     'Motorola',      'Philips',           '2E',
          'Fly',      'Samsung',    'Prestigio',      'myPhone',
   'BlackBerry',      'KENEKSI',       'Maxcom',       'HUAWEI',
       'Vernee',      'General',       'Globex',      'Smartex',
       'Google',         'ASUS',         'Land',        'MAFAM',
        'Jinga',     'Vodafone',    'Microsoft',     'iOutdoor',
     'Elephone',          'HTC',        'Viaan',         'vivo',
         'Sony',       'LEAGOO',         'Nomi',        'Apple']
Length: 64, dtype: str

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
977,977,Sigma mobile,X-style S3500 sKai Black,KAIOS,832,1036,899.0,1059.0,42,2.4,4.0,2000.0,19-Sep

In [49]:
dff.isnull().sum()
df.duplicated().sum()
df.drop_duplicates()

,Unnamed: 0,brand_name,model_name,os,popularity,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,NaN,NaN,10,5.71,16.0,3000.0,20-Apr
...,...,...,...,...,...,...,...,...,...,...,...,...
1219,1219,Apple,iPhone XS Max 64GB Gold (MT522),iOS,1101,16018.0,27900.0,61,6.50,64.0,3174.0,18-Sep
1220,1220,Apple,iPhone XS Max Dual Sim 64GB Gold (MT732),iOS,530,21939.0,33720.0,28,6.50,64.0,3174.0,18-Sep
1221,1221,HUAWEI,nova 5T 6/128GB Black (51094MEU),Android,1174,7999.0,9999.0,18,6.26,128.0,3750.0,19-Nov
1222,1222,ZTE,nubia Red Magic 5G 8/128GB Black,Android,752,18500.0,19010.0,2,6.65,128.0,4500.0,20-Oct
1223,1223,Sigma mobile,x-style 35 Screen,NaN,952,785.0,944.0,75,3.50,NaN,1750.0,20-Jan

In [50]:
dff.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    964 non-null    float64
 7   highest_price   964 non-null    float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 124.4 KB

In [51]:
dff.head(10)

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr
5,5,Honor,10 6/64GB Black,Android,71,10865,10631.0,11099.0,2,5.80,64.0,3400.0,18-Jun
6,6,Honor,10 Lite 3/32GB Blue,Android,424,3999,NaN,NaN,2,6.21,32.0,3400.0,18-Dec
7,7,Honor,10 Lite 4/64GB Black,Android,134,4973,4733.0,5295.0,6,6.21,64.0,3400.0,19-Jan
8,8,Honor,10 lite 3/128GB Blue,Android,477,5100,4990.0,5222.0,3,6.21,128.0,3400.0,21-Jan
9,9,Honor,10 lite 3/64GB Black,Android,215,4948,4646.0,5372.0,8,6.21,64.0,3400.0,18-Dec

In [52]:
dff.groupby("brand_name")["highest_price"].transform("mean")
dff.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    964 non-null    float64
 7   highest_price   964 non-null    float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 124.4 KB

In [53]:
dff.groupby("brand_name")["lowest_price"].transform("mean")
dff.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    964 non-null    float64
 7   highest_price   964 non-null    float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 124.4 KB

In [54]:
dff.head()

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr

In [55]:
dff.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    964 non-null    float64
 7   highest_price   964 non-null    float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 124.4 KB

In [56]:
dff.dropna(subset=['os'])

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1218,1218,Apple,iPhone XS Max 512GB Space Gray (MT622),iOS,842,27190,21150.0,30200.0,47,6.50,512.0,3174.0,18-Sep
1219,1219,Apple,iPhone XS Max 64GB Gold (MT522),iOS,1101,22685,16018.0,27900.0,61,6.50,64.0,3174.0,18-Sep
1220,1220,Apple,iPhone XS Max Dual Sim 64GB Gold (MT732),iOS,530,24600,21939.0,33720.0,28,6.50,64.0,3174.0,18-Sep
1221,1221,HUAWEI,nova 5T 6/128GB Black (51094MEU),Android,1174,8804,7999.0,9999.0,18,6.26,128.0,3750.0,19-Nov
1222,1222,ZTE,nubia Red Magic 5G 8/128GB Black,Android,752,18755,18500.0,19010.0,2,6.65,128.0,4500.0,20-Oct

In [57]:
dff.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    964 non-null    float64
 7   highest_price   964 non-null    float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 124.4 KB

In [58]:
dff.isnull().sum()

Unnamed: 0          0
brand_name          0
model_name          0
os                197
popularity          0
best_price          0
lowest_price      260
highest_price     260
sellers_amount      0
screen_size         2
memory_size       112
battery_size       10
release_date        0
dtype: int64

In [59]:
dff = dff.dropna(subset=['os'])
dff.info()

<class 'pandas.DataFrame'>
Index: 1027 entries, 0 to 1222
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1027 non-null   int64
 1   brand_name      1027 non-null   str
 2   model_name      1027 non-null   str
 3   os              1027 non-null   str
 4   popularity      1027 non-null   int64
 5   best_price      1027 non-null   int64
 6   lowest_price    791 non-null    float64
 7   highest_price   791 non-null    float64
 8   sellers_amount  1027 non-null   int64
 9   screen_size     1026 non-null   float64
 10  memory_size     1027 non-null   float64
 11  battery_size    1017 non-null   float64
 12  release_date    1027 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 112.3 KB

In [60]:
dff.isnull().sum()

Unnamed: 0          0
brand_name          0
model_name          0
os                  0
popularity          0
best_price          0
lowest_price      236
highest_price     236
sellers_amount      0
screen_size         1
memory_size         0
battery_size       10
release_date        0
dtype: int64