In [2]:
print("Nitesh")

Nitesh

In [5]:
import pandas as pd

# reading file
df = pd.read_csv("Mobile_data.csv")

# dataframe information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    964 non-null    float64
 7   highest_price   964 non-null    float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 124.4 KB

In [7]:
df.head()

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr

In [ ]:
df.isnull().sum()
df.duplicated().sum()  #it shows how many dupliates are there 
df.drop_duplicates()  # if there is dupicate it will remove that.

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1219,1219,Apple,iPhone XS Max 64GB Gold (MT522),iOS,1101,22685,16018.0,27900.0,61,6.50,64.0,3174.0,18-Sep
1220,1220,Apple,iPhone XS Max Dual Sim 64GB Gold (MT732),iOS,530,24600,21939.0,33720.0,28,6.50,64.0,3174.0,18-Sep
1221,1221,HUAWEI,nova 5T 6/128GB Black (51094MEU),Android,1174,8804,7999.0,9999.0,18,6.26,128.0,3750.0,19-Nov
1222,1222,ZTE,nubia Red Magic 5G 8/128GB Black,Android,752,18755,18500.0,19010.0,2,6.65,128.0,4500.0,20-Oct
1223,1223,Sigma mobile,x-style 35 Screen,NaN,952,907,785.0,944.0,75,3.50,NaN,1750.0,20-Jan

In [11]:
# print( "the total  brands are :", df["brand_name"].nunique())
# df["brand_name"].unique()
# df["os"].values_counts()

print("The total brands are :", df["brand_name"].nunique())

print(df["brand_name"].unique())

print(df["os"].value_counts())

The total brands are : 64
<StringArray>
[     'ALCATEL',        'Nokia',        'Honor',        'Meizu',
       'realme',      'OnePlus',       'Archos',      'Ulefone',
          'AGM',         'OPPO',        'Astro',       'Rezone',
    'Blackview',       'Bravis',          'NUU',       'Lenovo',
      'UMIDIGI',    'Assistant',    'Crosscall',        'Sharp',
         'ERGO',        'Tecno',          'CAT',       'DOOGEE',
       'Xiaomi',          'ZTE',      'Oukitel',        'Cubot',
       'S-TELL', 'Sigma mobile',      'Coolpad',       'Bluboo',
           'LG',     'Motorola',      'Philips',           '2E',
          'Fly',      'Samsung',    'Prestigio',      'myPhone',
   'BlackBerry',      'KENEKSI',       'Maxcom',       'HUAWEI',
       'Vernee',      'General',       'Globex',      'Smartex',
       'Google',         'ASUS',         'Land',        'MAFAM',
        'Jinga',     'Vodafone',    'Microsoft',     'iOutdoor',
     'Elephone',          'HTC',        'Viaan',         'vivo',
         'Sony',       'LEAGOO',         'Nomi',        'Apple']
Length: 64, dtype: str
os
Android         915
iOS             103
OxygenOS          3
WindowsPhone      3
EMUI              2
KAIOS             1
Name: count, dtype: int64

In [19]:
df.describe()

,Unnamed: 0,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size
count,1224.000000,1224.000000,1224.000000,964.000000,964.000000,1224.000000,1222.000000,1112.000000,1214.000000
mean,611.500000,612.500000,7941.206699,7716.018672,9883.410788,16.743464,5.394378,95.700059,3608.201812
std,353.482673,353.482673,8891.836260,8560.959059,11514.936818,20.597006,1.476991,111.922576,1668.268774
min,0.000000,1.000000,214.000000,198.000000,229.000000,1.000000,1.400000,0.003200,460.000000
25%,305.750000,306.750000,2599.750000,2399.000000,2887.000000,2.000000,5.162500,32.000000,2900.000000
50%,611.500000,612.500000,4728.000000,4574.000000,5325.500000,8.000000,6.000000,64.000000,3687.000000
75%,917.250000,918.250000,9323.000000,9262.250000,12673.750000,26.000000,6.400000,128.000000,4400.000000
max,1223.000000,1224.000000,56082.000000,49999.000000,69999.000000,125.000000,8.100000,1000.000000,18800.000000

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    964 non-null    float64
 7   highest_price   964 non-null    float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 124.4 KB

In [24]:
df['highest_price'].fillna(299, inplace=True)
df['highest_price'].notnull().sum()

/tmp/ipykernel_11274/977839184.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['highest_price'].fillna(299, inplace=True)

np.int64(964)

In [26]:
newdf=df.fillna(30)
newdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1224 non-null   object
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   1224 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1224 non-null   float64
 10  memory_size     1224 non-null   float64
 11  battery_size    1224 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), object(1), str(3)
memory usage: 124.4+ KB

In [28]:
newdf = df.fillna(30)
newdf.info()
x = df['highest_price'].mean()
newdf=df.fillna(x)

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1224 non-null   object
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   1224 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1224 non-null   float64
 10  memory_size     1224 non-null   float64
 11  battery_size    1224 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), object(1), str(3)
memory usage: 124.4+ KB

In [32]:
df['highest_price'] = df['highest_price'].fillna(
    df.groupby('brand_name')['highest_price'].transform('mean'))
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    964 non-null    float64
 7   highest_price   1206 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 124.4 KB

In [38]:
df["highes_price"] = df['highest_price'].fillna(df['highest_price'].mean())
df.info()
df.head

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   1206 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
 13  highes_price    1224 non-null   float64
dtypes: float64(6), int64(4), str(4)
memory usage: 134.0 KB

<bound method NDFrame.head of       Unnamed: 0    brand_name                                    model_name  \
0              0       ALCATEL          1 1/8GB Bluish Black (5033D-2JALUAA)
1              1       ALCATEL  1 5033D 1/16GB Volcano Black (5033D-2LALUAF)
2              2       ALCATEL  1 5033D 1/16GB Volcano Black (5033D-2LALUAF)
3              3       ALCATEL  1 5033D 1/16GB Volcano Black (5033D-2LALUAF)
4              4         Nokia                           1.3 1/16GB Charcoal
...          ...           ...                                           ...
1219        1219         Apple               iPhone XS Max 64GB Gold (MT522)
1220        1220         Apple      iPhone XS Max Dual Sim 64GB Gold (MT732)
1221        1221        HUAWEI              nova 5T 6/128GB Black (51094MEU)
1222        1222           ZTE              nubia Red Magic 5G 8/128GB Black
1223        1223  Sigma mobile                             x-style 35 Screen

           os  popularity  best_price  lowest_price  highest_price  \
0     Android         422        1690   1529.000000    1819.000000
1     Android         323        1803   1659.000000    2489.000000
2     Android         299        1803   1659.000000    2489.000000
3     Android         287        1803   1659.000000    2489.000000
4     Android        1047        1999   7716.018672    3185.263158
...       ...         ...         ...           ...            ...
1219      iOS        1101       22685  16018.000000   27900.000000
1220      iOS         530       24600  21939.000000   33720.000000
1221  Android        1174        8804   7999.000000    9999.000000
1222  Android         752       18755  18500.000000   19010.000000
1223      NaN         952         907    785.000000     944.000000

      sellers_amount  screen_size  memory_size  battery_size release_date  \
0                 36         5.00          8.0        2000.0       20-Oct
1                 36         5.00         16.0        2000.0       20-Sep
2                 36         5.00         16.0        2000.0       20-Sep
3                 36         5.00         16.0        2000.0       20-Sep
4                 10         5.71         16.0        3000.0       20-Apr
...              ...          ...          ...           ...          ...
1219              61         6.50         64.0        3174.0       18-Sep
1220              28         6.50         64.0        3174.0       18-Sep
1221              18         6.26        128.0        3750.0       19-Nov
1222               2         6.65        128.0        4500.0       20-Oct
1223              75         3.50          NaN        1750.0       20-Jan

      highes_price
0      1819.000000
1      2489.000000
2      2489.000000
3      2489.000000
4      3185.263158
...            ...
1219  27900.000000
1220  33720.000000
1221   9999.000000
1222  19010.000000
1223    944.000000

[1224 rows x 14 columns]>

In [40]:
df["lowest_price"] = df['lowest_price'].fillna(df['lowest_price'].mean())
df.info()
df.head

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   1206 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
 13  highes_price    1224 non-null   float64
dtypes: float64(6), int64(4), str(4)
memory usage: 134.0 KB

<bound method NDFrame.head of       Unnamed: 0    brand_name                                    model_name  \
0              0       ALCATEL          1 1/8GB Bluish Black (5033D-2JALUAA)
1              1       ALCATEL  1 5033D 1/16GB Volcano Black (5033D-2LALUAF)
2              2       ALCATEL  1 5033D 1/16GB Volcano Black (5033D-2LALUAF)
3              3       ALCATEL  1 5033D 1/16GB Volcano Black (5033D-2LALUAF)
4              4         Nokia                           1.3 1/16GB Charcoal
...          ...           ...                                           ...
1219        1219         Apple               iPhone XS Max 64GB Gold (MT522)
1220        1220         Apple      iPhone XS Max Dual Sim 64GB Gold (MT732)
1221        1221        HUAWEI              nova 5T 6/128GB Black (51094MEU)
1222        1222           ZTE              nubia Red Magic 5G 8/128GB Black
1223        1223  Sigma mobile                             x-style 35 Screen

           os  popularity  best_price  lowest_price  highest_price  \
0     Android         422        1690   1529.000000    1819.000000
1     Android         323        1803   1659.000000    2489.000000
2     Android         299        1803   1659.000000    2489.000000
3     Android         287        1803   1659.000000    2489.000000
4     Android        1047        1999   7716.018672    3185.263158
...       ...         ...         ...           ...            ...
1219      iOS        1101       22685  16018.000000   27900.000000
1220      iOS         530       24600  21939.000000   33720.000000
1221  Android        1174        8804   7999.000000    9999.000000
1222  Android         752       18755  18500.000000   19010.000000
1223      NaN         952         907    785.000000     944.000000

      sellers_amount  screen_size  memory_size  battery_size release_date  \
0                 36         5.00          8.0        2000.0       20-Oct
1                 36         5.00         16.0        2000.0       20-Sep
2                 36         5.00         16.0        2000.0       20-Sep
3                 36         5.00         16.0        2000.0       20-Sep
4                 10         5.71         16.0        3000.0       20-Apr
...              ...          ...          ...           ...          ...
1219              61         6.50         64.0        3174.0       18-Sep
1220              28         6.50         64.0        3174.0       18-Sep
1221              18         6.26        128.0        3750.0       19-Nov
1222               2         6.65        128.0        4500.0       20-Oct
1223              75         3.50          NaN        1750.0       20-Jan

      highes_price
0      1819.000000
1      2489.000000
2      2489.000000
3      2489.000000
4      3185.263158
...            ...
1219  27900.000000
1220  33720.000000
1221   9999.000000
1222  19010.000000
1223    944.000000

[1224 rows x 14 columns]>

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   1206 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
 13  highes_price    1224 non-null   float64
dtypes: float64(6), int64(4), str(4)
memory usage: 134.0 KB

In [45]:
df.head(10)

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date,highes_price
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.000000,1819.000000,36,5.00,8.0,2000.0,20-Oct,1819.000000
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.000000,2489.000000,36,5.00,16.0,2000.0,20-Sep,2489.000000
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.000000,2489.000000,36,5.00,16.0,2000.0,20-Sep,2489.000000
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.000000,2489.000000,36,5.00,16.0,2000.0,20-Sep,2489.000000
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,7716.018672,3185.263158,10,5.71,16.0,3000.0,20-Apr,3185.263158
5,5,Honor,10 6/64GB Black,Android,71,10865,10631.000000,11099.000000,2,5.80,64.0,3400.0,18-Jun,11099.000000
6,6,Honor,10 Lite 3/32GB Blue,Android,424,3999,7716.018672,5385.789474,2,6.21,32.0,3400.0,18-Dec,5385.789474
7,7,Honor,10 Lite 4/64GB Black,Android,134,4973,4733.000000,5295.000000,6,6.21,64.0,3400.0,19-Jan,5295.000000
8,8,Honor,10 lite 3/128GB Blue,Android,477,5100,4990.000000,5222.000000,3,6.21,128.0,3400.0,21-Jan,5222.000000
9,9,Honor,10 lite 3/64GB Black,Android,215,4948,4646.000000,5372.000000,8,6.21,64.0,3400.0,18-Dec,5372.000000

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   1206 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
 13  highes_price    1224 non-null   float64
dtypes: float64(6), int64(4), str(4)
memory usage: 134.0 KB

In [53]:
df=df.dropna(subset=['os'])
df.info()

<class 'pandas.DataFrame'>
Index: 1027 entries, 0 to 1222
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1027 non-null   int64
 1   brand_name      1027 non-null   str
 2   model_name      1027 non-null   str
 3   os              1027 non-null   str
 4   popularity      1027 non-null   int64
 5   best_price      1027 non-null   int64
 6   lowest_price    1027 non-null   float64
 7   highest_price   1015 non-null   float64
 8   sellers_amount  1027 non-null   int64
 9   screen_size     1026 non-null   float64
 10  memory_size     1027 non-null   float64
 11  battery_size    1017 non-null   float64
 12  release_date    1027 non-null   str
 13  highes_price    1027 non-null   float64
dtypes: float64(6), int64(4), str(4)
memory usage: 120.4 KB

In [58]:
df=df.dropna(subset=['screen_size'])
df=df.dropna(subset=['battery_size'])
df.info()

<class 'pandas.DataFrame'>
Index: 1016 entries, 0 to 1222
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1016 non-null   int64
 1   brand_name      1016 non-null   str
 2   model_name      1016 non-null   str
 3   os              1016 non-null   str
 4   popularity      1016 non-null   int64
 5   best_price      1016 non-null   int64
 6   lowest_price    1016 non-null   float64
 7   highest_price   1004 non-null   float64
 8   sellers_amount  1016 non-null   int64
 9   screen_size     1016 non-null   float64
 10  memory_size     1016 non-null   float64
 11  battery_size    1016 non-null   float64
 12  release_date    1016 non-null   str
 13  highes_price    1016 non-null   float64
dtypes: float64(6), int64(4), str(4)
memory usage: 119.1 KB

In [61]:
df.isnull().sum()

Unnamed: 0        0
brand_name        0
model_name        0
os                0
popularity        0
best_price        0
lowest_price      0
highest_price     0
sellers_amount    0
screen_size       0
memory_size       0
battery_size      0
release_date      0
highes_price      0
dtype: int64

In [62]:
df=df.dropna(subset=['highest_price'])
df.info()

<class 'pandas.DataFrame'>
Index: 1004 entries, 0 to 1222
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1004 non-null   int64
 1   brand_name      1004 non-null   str
 2   model_name      1004 non-null   str
 3   os              1004 non-null   str
 4   popularity      1004 non-null   int64
 5   best_price      1004 non-null   int64
 6   lowest_price    1004 non-null   float64
 7   highest_price   1004 non-null   float64
 8   sellers_amount  1004 non-null   int64
 9   screen_size     1004 non-null   float64
 10  memory_size     1004 non-null   float64
 11  battery_size    1004 non-null   float64
 12  release_date    1004 non-null   str
 13  highes_price    1004 non-null   float64
dtypes: float64(6), int64(4), str(4)
memory usage: 117.7 KB

In [64]:
df.isnull().sum()

Unnamed: 0        0
brand_name        0
model_name        0
os                0
popularity        0
best_price        0
lowest_price      0
highest_price     0
sellers_amount    0
screen_size       0
memory_size       0
battery_size      0
release_date      0
highes_price      0
dtype: int64

In [67]:
df.describe()

,Unnamed: 0,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,highes_price
count,1004.000000,1004.000000,1004.000000,1004.000000,1004.000000,1004.000000,1004.000000,1004.000000,1004.000000,1004.000000
mean,618.858566,655.301793,9338.481076,8880.043011,11227.532207,15.981076,5.999203,104.183267,3993.383466,11227.532207
std,340.946419,355.174036,9006.116317,7650.739651,10818.709026,21.220361,0.621079,112.772149,1332.401532,10818.709026
min,0.000000,2.000000,840.000000,899.000000,446.583333,1.000000,2.400000,4.000000,1300.000000,446.583333
25%,348.750000,351.750000,3528.500000,3999.000000,4137.750000,2.000000,5.500000,32.000000,3020.000000,4137.750000
50%,624.500000,680.500000,5572.000000,7697.509336,6471.812500,7.000000,6.165000,64.000000,4000.000000,6471.812500
75%,889.250000,967.250000,12078.250000,8475.500000,15491.733333,22.000000,6.500000,128.000000,4500.000000,15491.733333
max,1222.000000,1224.000000,55338.000000,45799.000000,64999.000000,125.000000,8.100000,1000.000000,13000.000000,64999.000000

In [72]:
df['lowest_price'] = df['lowest_price'].astype(int)
df['release_date'] = pd.to_datetime(df['release_date'])
df.info()

<class 'pandas.DataFrame'>
Index: 1004 entries, 0 to 1222
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1004 non-null   int64
 1   brand_name      1004 non-null   str
 2   model_name      1004 non-null   str
 3   os              1004 non-null   str
 4   popularity      1004 non-null   int64
 5   best_price      1004 non-null   int64
 6   lowest_price    1004 non-null   int64
 7   highest_price   1004 non-null   float64
 8   sellers_amount  1004 non-null   int64
 9   screen_size     1004 non-null   float64
 10  memory_size     1004 non-null   float64
 11  battery_size    1004 non-null   float64
 12  release_date    1004 non-null   datetime64[us]
 13  highes_price    1004 non-null   float64
dtypes: datetime64[us](1), float64(5), int64(5), str(3)
memory usage: 117.7 KB

In [79]:
df= df.rename(columns={'highest_price': 'Expensive_price'})
df.columns = df.columns.str.replace("_"," ")
# df.info()
df.head()

,Unnamed: 0,brand name,model name,os,popularity,best price,lowest price,highest price,sellers amount,screen size,memory size,battery size,release date,highes price
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529,1819.000000,36,5.00,8.0,2000.0,1-10-20,1819.000000
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659,2489.000000,36,5.00,16.0,2000.0,1-09-20,2489.000000
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659,2489.000000,36,5.00,16.0,2000.0,1-09-20,2489.000000
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659,2489.000000,36,5.00,16.0,2000.0,1-09-20,2489.000000
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,7716,3185.263158,10,5.71,16.0,3000.0,1-04-20,3185.263158